helmGlobals:
  chartHome: ../../base/
  
helmCharts:
  - name: alloy
    releaseName: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.2.1
    valuesFile: values.yaml
    namespace: observability

bases:
  - ../../base/