helmGlobals:
  chartHome: ../../base/
  
helmCharts:
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    version: 9.3.2
    valuesFile: values.yaml
    namespace: observability