helmGlobals:
  chartHome: ../../base/
  
helmCharts:
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    version: 12.1.7
    valuesFile: values.yaml
    namespace: observability