tempo:
  resources:
    requests:
      cpu: "1"
      memory: "100Mi"
    limits:
      cpu: "1"
      memory: "500Mi"
  reportingEnabled: true
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write"

  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_http:
          endpoint: 0.0.0.0:14268
    opencensus:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

persistence:
  enabled: true
  enableStatefulSetAutoDeletePVC: false
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 5Gi