helmGlobals:
  chartHome: ../../base/
helmCharts:
  - name: cert-manager
    repo: https://charts.bitnami.com/bitnami
    releaseName: cert-manager
    valuesFile: app-certs-values.yaml
    version: 1.5.13
    includeCRDs: true
    namespace: cert-manager
  - name: app-certs
    releaseName: app-certs
    valuesFile: app-certs-values.yaml
    namespace: cert-manager
