helmGlobals:
  chartHome: ../../base/
helmCharts:
  - name: cert-manager
    repo: https://charts.bitnami.com/bitnami
    releaseName: cert-manager
    valuesFile: values.yaml
    version: 1.5.13
    namespace: certs

bases:
  - ../../base/

patches:
  - path: namespace-patch.yaml
    target:
      group: cert-manager
      version: v1
      kind: Certificate
      name: hipstershop-tls-cert
  - path: namespace-patch.yaml
    target:
      group: cert-manager
      version: v1
      kind: Issuer
      name: selfsigned-issuer