helmGlobals:
  chartHome: ../../base/
  
helmCharts:
  - name: opentelemetry-operator
    releaseName: opentelemetry-operator
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.93.0
    valuesFile: values.yaml
    namespace: observability

bases:
  - ../../base/

patches:
  - path: namespace-patch.yaml
    target:
      group: opentelemetry
      version: v1beta1
      kind: OpenTelemetryCollector
      name: otel-collector
  - path: namespace-patch.yaml
    target:
      group: opentelemetry
      version: v1alpha1
      kind: Instrumentation
      name: auto-instrumenter