apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hipstershop-tls-cert
  namespace: hipstershop
spec:
  secretName: hipstershop-tls-cert-secret
  dnsNames:
    - 'store.hipstershop.com'
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer